.Dd December 9 2023
.Dt GRAB 1
.Os
.Sh NAME
.Nm grab
.Nd search for patterns in files
.Sh SYNOPSIS
.Nm
.Op Fl z
.Ar pattern
.Op Ar
.Sh DESCRIPTION
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Sh SEE ALSO
.Xr grep 1
.Rs
.%A Rob Pike
.%D 1987
.%T Structural Regular Expressions
.%U https://doc.cat-v.org/bell_labs/structural_regexps/se.pdf
.Re
.Sh AUTHORS
.An Thomas Voss Aq Mt mail@thomasvoss.com
